# Unix & Apple part
FIND_PACKAGE(TIFF REQUIRED)
FIND_PACKAGE(exiv2 REQUIRED)
FIND_PACKAGE(OpenEXR REQUIRED)
FIND_PACKAGE(jpeg REQUIRED)
FIND_PACKAGE(LCMS2 REQUIRED)

FIND_PACKAGE(Boost COMPONENTS thread unit_test_framework REQUIRED)
ADD_DEFINITIONS(-Wall)
