INCLUDE_DIRECTORIES("${CMAKE_SOURCE_DIR}/include")

IF(MSVC)
INCLUDE("${CMAKE_SOURCE_DIR}/cmake/FindLibHDRDepsWin.cmake")
ELSE()
INCLUDE("${CMAKE_SOURCE_DIR}/cmake/FindLibHDRDepsUnix.cmake")
ENDIF()

# GIL contributions
INCLUDE_DIRECTORIES("/Users/Davide/Luminance/gil-contributions/gil_2")

INCLUDE_DIRECTORIES("${CMAKE_SOURCE_DIR}/include")
INCLUDE_DIRECTORIES(${Boost_INCLUDE_DIRS})
INCLUDE_DIRECTORIES(${TIFF_INCLUDE_DIR})
INCLUDE_DIRECTORIES(${EXIV2_INCLUDE_DIR})
INCLUDE_DIRECTORIES(${OPENEXR_INCLUDE_DIR})
INCLUDE_DIRECTORIES("${OPENEXR_INCLUDE_DIR}/OpenEXR")
INCLUDE_DIRECTORIES(${JPEG_INCLUDE_DIR})
INCLUDE_DIRECTORIES(${LCMS2_INCLUDE_DIR})

LINK_DIRECTORIES(${Boost_LIBRARY_DIRS})
LINK_DIRECTORIES(${TIFF_LIBRARY_DIRS})
LINK_DIRECTORIES(${JPEG_LIBRARY_DIRS})
LINK_DIRECTORIES(${LCMS2_LIBRARY_DIRS})
